service: ft-quiz

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

functions:
  quiz:
    handler: handler.quiz
    events:
      - http:
          path: quiz
          method: get
