service: ftlabs-quiz

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  timeout: 30
  environment:
    LANTERN_API_KEY: "${file(./serverless.env.yml):dev.LANTERN_API_KEY}"
  stackTags:
    environment: p
    teamDL: ftlabs@ft.com
    systemCode: ftlabs-quiz
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - comprehend:DetectKeyPhrases
      Resource: "*"

functions:
  ftlabs-quiz:
    handler: handler.ftlabsQuiz
    events:
      - http:
          path: ftlabsQuiz
          method: get
