service: ftlabs-quiz

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  stackTags:
    environment: p
    teamDL: ftlabs@ft.com
    systemCode: ftlabs-quiz

functions:
  ftlabs-quiz:
    handler: handler.ftlabsQuiz
    events:
      - http:
          path: ftlabsQuiz
          method: get
